services:
  mysql:
    image: mysql:latest
    container_name: mysql_agile_board_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3360:3306"
    volumes:
      - mysql_agileboard_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  

volumes:
  mysql_agileboard_data:
